read.csv("/Users/admin/Documents/Skimming/tree_of_life/tree_k_titration_recalc_viral/summary_report_kraken_viral_dist_unmasked_0.0_corrected_k35.csv")
head(read.csv("/Users/admin/Documents/Skimming/tree_of_life/tree_k_titration_recalc_viral/summary_report_kraken_viral_dist_unmasked_0.0_corrected_k35.csv"))
d=read.csv("/Users/admin/Documents/Skimming/tree_of_life/tree_k_titration_recalc_viral/summary_report_kraken_viral_dist_unmasked_0.0_corrected_k35.csv")
names(d)
head(d[,c(3,38,8,30)])
melt(head(d[,c(3,38,8,30)]))
melt(head(d[,c(3,38,8,30)]),id.vars = )
head(d[,c(3,38,8,30)])
melt(head(d[,c(8,30,3,38)]))
melt(head(d[,c(8,30,3,38)]))
head(d[,c(3,38,8,30)])
melt(head(d[,c(8,30,3,38)]),id.vars = "")
names(d)
melt(head(d[,c(2,8,30,3,38)]),id.vars = "Exclude")
melt(head(d[,c(2,8,30,3,38)]),id.vars = "Exclude",value.name = c(" prct_species","C_sequences_prct"))
melt(head(d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct"))
melt(head(d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species"))
melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species"))
head(melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species"))
)
qplot(value,C_sequences_prct,color=prct_species,data=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species")))+facet_wrap(~variable)+theme_bw()
qplot(value,C_sequences_prct,color=prct_species,data=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species")))+facet_wrap(~variable)+theme_bw()+geom_smooth()
qplot(value,C_sequences_prct,color=prct_species,data=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species")))+facet_wrap(~variable)+theme_bw()+geom_smooth(SE=F)
qplot(value,C_sequences_prct,color=prct_species,data=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species")))+facet_wrap(~variable)+theme_bw()+geom_smooth(se =F)
qplot(value,C_sequences_prct,color=prct_species,data=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species")))+facet_wrap(~variable)+theme_bw()+geom_smooth(se =F)
?geom_smooth
qplot(value,C_sequences_prct,color=prct_species,data=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species")))+facet_wrap(~variable)+theme_bw()+geom_smooth(se =F,method = "gm")
qplot(value,C_sequences_prct,color=prct_species,data=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species")))+facet_wrap(~variable)+theme_bw()+geom_smooth(se =F,method = "glm")
?geom_smooth
qplot(value,C_sequences_prct,color=prct_species,data=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species")))+facet_wrap(~variable)+theme_bw()+geom_smooth(se =F,method = "gam")
?geom_smooth
qplot(value,C_sequences_prct,color=prct_species,data=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species")))+facet_wrap(~variable)+theme_bw()+geom_smooth(se =F,method = MASS::rlm )
qplot(value,C_sequences_prct,color=prct_species,data=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species")))+facet_wrap(~variable)+theme_bw()+geom_smooth(se =F)
?geom_smooth
qplot(value,C_sequences_prct,color=prct_species,data=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species")))+facet_wrap(~variable)+theme_bw()+geom_smooth(se =F)
m=melt((d[,c(2,8,30,3,38)]),id.vars = c("Exclude","C_sequences_prct","prct_species"))
m[m$variable=="mash_10k_distance",]
m[m$variable=="mash_10K_distance",]
m[m$variable=="mash_10K_distance" & m$value>0.5,]
m[m$variable!="mash_10K_distance" | m$value<0.5,]
m[m$variable!="mash_10K_distance" | m$value<0.5,]
qplot(value,C_sequences_prct,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable)+theme_bw()+geom_smooth(se =F)
qplot(value,C_sequences_prct,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x")+theme_bw()+geom_smooth(se =F)
qplot(value,C_sequences_prct,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x")+theme_classic()+geom_smooth(se =F)
qplot(value,C_sequences_prct,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x")+theme_bw()+geom_smooth(se =F)
qplot(value,C_sequences_prct,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x")+theme_bw()+geom_smooth(se =F,color="red")
qplot(value,C_sequences_prct,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x")+theme_bw()+geom_smooth(se =F,color="red")+xlab("Percent classified")+scale_y_continuous(labels=percent)
require(scales)
qplot(value,C_sequences_prct,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x")+theme_bw()+geom_smooth(se =F,color="red")+xlab("Percent classified")+scale_y_continuous(labels=percent)
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x")+theme_bw()+geom_smooth(se =F,color="red")+xlab("Percent classified")+scale_y_continuous(labels=percent)
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x")+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x")+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest neighbor")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x")+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) c("1","2"))+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) c("1","2")[x])+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) print(x))+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x[1]="1";print(x)})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x[1,1]="1";print(x)})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {print(x)})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {print(x);x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
?facet_wrap
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x")+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {print(x);x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x[1,"variable"]="d";print(x);x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x[1,"variable"]="d";print(x[1,"variable"]);x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x[1,"variable"]="d";print(x$variable);x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x$"variable"=c("d","a");print(x$variable);x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x$"variable"=c("Phylogenetic","Sequence (Mash computed)");x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x$"variable"=c("Phylogenetic","Sequence (Mash computed)");x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")+scale_color_continuous(name="Classified at species level")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x$"variable"=c("Phylogenetic","Sequence (Mash computed)");x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")+scale_color_continuous(name="Classified at species level",labels=percent)
qplot(value,C_sequences_prct/100,color=prct_species/100,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x$"variable"=c("Phylogenetic","Sequence (Mash computed)");x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")+scale_color_continuous(name="Classified at species level",labels=percent)
qplot(value,C_sequences_prct/100,color=prct_species/100,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x$"variable"=c("Phylogenetic","Sequence (Mash computed)");x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")+scale_color_continuous(name="Classified at species level",labels=percent)+theme(legend.position = "bottom")
qplot(value,C_sequences_prct/100,color=prct_species/100,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x$"variable"=c("Phylogenetic","Sequence (Mash computed)");x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")+scale_color_continuous(name="Classified at species level",labels=percent,breaks=c(0.1,0.5,1))+theme(legend.position = "bottom")
qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x$"variable"=c("Phylogenetic","Sequence (Mash computed)");x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")+scale_color_continuous(name="Classified at species level")+theme(legend.position = "bottom")
graph = qplot(value,C_sequences_prct/100,color=prct_species,data=m[m$variable!="mash_10K_distance" | m$value<0.5,])+facet_wrap(~variable,scales = "free_x",labeller = function(x) {x$"variable"=c("Phylogenetic","Sequence (Mash computed)");x})+theme_bw()+geom_smooth(se =F,color="red")+ylab("Percent classified")+scale_y_continuous(labels=percent)+xlab("Distance to the closest reference species")+scale_color_continuous(name="Classified at species level")+theme(legend.position = "bottom")
ggsave("graph3.pdf")
ggsave("graph3.pdf",width = 6, height = 4)
ggsave("graph3.pdf",width = 5, height = 3)
ggsave("graph3.pdf",width = 5, height = 3.5)
ggsave("graph3.pdf",width = 5.5, height = 3.5)
