head(read.csv(" /Users/admin/Documents/Skimming/tree_of_life/tree_k_titration_recalc_viral/export_df_all_data.csv "))
head(read.csv(" /Users/admin/Documents/Skimming/tree_of_life/tree_k_titration_recalc_viral/export_df_all_data.csv"))
head(read.csv("/Users/admin/Documents/Skimming/tree_of_life/tree_k_titration_recalc_viral/export_df_all_data.csv"))
r=read.csv("export_df_all_data_extended.csv")
names(r)
qplot(FPR,recall,shape=as.factor(k),color=as.factor(paste(bin_min,bin_max)),group=bin,data=r[r$FPR<0.2&r$confidence_level<0.4,])+facet_wrap(~confidence_level,nrow=1)+geom_line()+scale_shape_manual(values=1:10)+scale_color_brewer(palette = "Paired")+theme_bw()+theme(legend.position = "bottom")
paste(r$bin_min,r$bin_max,sep=",")
options(digits=2)
paste(r$bin_min,r$bin_max,sep=",")
formate(r$bin_mean,digits=1)
format(r$bin_mean,digits=1)
format(r$bin_mean,digits=1)
paste(format(r$bin_mean,digits=1),format(r$bin_max,digits=1),sep=",")
paste(format(r$bin_mean,digits=1),format(r$bin_max,digits=1),sep="-")
paste(format(r$bin_mean,digits=0),format(r$bin_max,digits=0),sep="-")
paste(format(r$bin_mean,digits=1),format(r$bin_max,digits=1),sep="-")
qplot(FPR,recall,shape=as.factor(-k),color=as.factor(bin),group=bin,data=r[r$FPR<0.2&r$confidence_level<0.4,])+facet_wrap(~confidence_level,nrow=1)+geom_line()+scale_shape_discrete(name="k",labels=rev(unique(r$k)))+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
ggsave("ROC-peralpha2.pdf",width = 9,height = 3.5)
qplot(FPR,recall,shape=as.factor(-k),color=as.factor(bin),group=bin,data=r[r$FPR<1.1&r$confidence_level<0.4,])+facet_wrap(~confidence_level,nrow=1)+geom_line()+scale_shape_discrete(name="k",labels=rev(unique(r$k)))+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
ggsave("ROC-peralpha-supplementary2.pdf",width = 9,height = 3.5)
qplot(FPR,recall,shape=as.factor(-k),color=as.factor(bin),group=bin,data=r[r$FPR<1.1&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~confidence_level,nrow=1)+geom_line()+scale_shape_discrete(name="k",labels=rev(unique(r$k)))+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
ggsave("ROC-peralpha-supplementary2.pdf",width = 9,height = 3.5)
qplot(FPR,recall,shape=as.factor(k),color=as.factor(bin),group=bin,data=r[r$FPR<1.1&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~confidence_level,nrow=1)+geom_line()+scale_shape_discrete(name="k")+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
qplot(FPR,recall,shape=as.factor(k),color=factor(bin),group=bin,data=r[r$FPR<1.1&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~confidence_level,nrow=1)+geom_line()+scale_shape_discrete(name="k")+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
ggsave("ROC-peralpha-supplementary2.pdf",width = 9,height = 3.5)
qplot(FPR,recall,shape=as.factor(k),color=factor(bin),group=bin,data=r[r$FPR<0.2&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~confidence_level,nrow=1)+geom_line()+scale_shape_discrete(name="k")+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
qplot(FPR,recall,shape=factor(k,levels = rev(unique(k))),color=factor(bin),group=bin,data=r[r$FPR<0.2&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~confidence_level,nrow=1)+geom_line()+scale_shape_discrete(name="k")+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
qplot(FPR,recall,shape=factor(k,levels = (unique(k))),color=factor(bin),group=bin,data=r[r$FPR<0.2&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~confidence_level,nrow=1)+geom_line()+scale_shape_discrete(name="k")+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
qplot(FPR,recall,shape=as.factor(-k),color=factor(bin),group=bin,data=r[r$FPR<0.2&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~confidence_level,nrow=1)+geom_line()+scale_shape_discrete(name="k",labels=c("35","32","29","28","27","26"))+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
ggsave("ROC-peralpha_extended.pdf",width = 9,height = 3.5)
qplot(FPR,recall,shape=as.factor(-k),color=factor(bin),group=bin,data=r[r$FPR<1.1&r$confidence_level<0.4&r$k!=20&r$k!=23,])+facet_wrap(~confidence_level,nrow=1)+geom_line()+scale_shape_discrete(name="k",labels=c("35","32","29","28","27","26"))+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
ggsave("ROC-peralpha-full_extended.pdf",width = 9,height = 3.5)
qplot(FPR,recall,shape=as.factor(confidence_level),color=factor(bin),group=bin,data=r[r$FPR<0.2&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~k,nrow=1)+geom_line()+scale_shape_discrete(name="k")+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
ggsave("ROC-perk_extended.pdf",width = 9,height = 3.5)
qplot(FPR,recall,shape=as.factor(confidence_level),color=factor(bin),group=bin,data=r[r$FPR<1.1&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~k,nrow=1)+geom_line()+scale_shape_discrete(name="k")+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
ggsave("ROC-perk-full_extended.pdf",width = 9,height = 3.5)
qplot(FPR,recall,shape=as.factor(confidence_level),color=factor(k),group=k,data=r[r$FPR<0.2&r$confidence_level<0.4&r$k!=20,])+
  facet_wrap(~bin,nrow=2,labeller = function(x) {x$bin=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25");x})+
  scale_shape_manual(name="confidence",values=c(1,0,2,6,5,4))+scale_color_brewer(palette = "Dark2", name="k")+
  theme_bw()+theme(legend.position = "bottom")+
  scale_x_continuous(breaks=c(0.01,0.09,0.17))
ggsave("ROC-perbin_extended.pdf",width=8,height = 4.5)
qplot(FPR,recall,shape=as.factor(confidence_level),color=factor(k),group=k,data=r[r$FPR<1.2&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~bin,nrow=2,labeller = function(x) {x$bin=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25");x})+scale_shape_discrete(name="confidence")+scale_color_brewer(palette = "Dark2", name="k")+theme_bw()+theme(legend.position = "bottom")+scale_x_continuous(breaks=c(0.01,0.04,0.07))
ggsave("ROC-perbin-full_extended.pdf",width=8,height = 4.5)
qplot(FPR,recall,shape=as.factor(confidence_level),color=factor(k),group=k,data=r[r$FPR<1.2&r$confidence_level<0.4&r$k!=20,])+
  facet_wrap(~bin,nrow=2,labeller = function(x) {x$bin=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25");x})+
  scale_shape_manual(name="confidence",values=c(1,0,2,6,5,4))+scale_color_brewer(palette = "Dark2", name="k")+
  theme_bw()+theme(legend.position = "bottom")+
  scale_x_continuous(breaks=c(0.2,0.5,0.8))
ggsave("ROC-perbin-full_extended.pdf",width=8,height = 4.5)
qplot(FPR,recall,shape=as.factor(confidence_level),color=factor(bin),group=bin,data=r[r$FPR<0.2&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~k,nrow=1)+geom_line()+scale_shape_discrete(name="confidence")+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
ggsave("ROC-perk_extended.pdf",width = 9,height = 3.5)
qplot(FPR,recall,shape=as.factor(confidence_level),color=factor(bin),group=bin,data=r[r$FPR<1.1&r$confidence_level<0.4&r$k!=20,])+facet_wrap(~k,nrow=1)+geom_line()+scale_shape_discrete(name="confidence")+scale_color_brewer(palette = "Paired", name="dist to closest match",labels=c("0","(0-1]","(1-2]","(2-3]","(3-5]","(5-10]","(10-15]","(15-20]","(20-25]",">25"))+theme_bw()+theme(legend.position = "bottom")
ggsave("ROC-perk-full_extended.pdf",width = 9,height = 3.5)
ggsave("ROC-perk-full_extended.pdf",width = 9,height = 3.5)
